### ISSUE TITLE
Integration with laravel and livewire

### ISSUE THREAD

**Issue by Jul000** [thinhbuzz/laravel-h-captcha#4]
Hello,

Thanks for your package. I m trying to add a Hcaptcha to a llivewire form but i have the same error *No property found for validation: [h-captcha-response]"

Is someone successfully add Hcaptcha to a livewire form ? Or have an tutorial ?

Thanks for your help

Julien

**Comment by thinhbuzz** [comment]
@Julien0510 can you please push an example repo?
